### PR TITLE
Add  -> None to many __init__s

### PR DESCRIPTION
**Pull request by gran4**
Fixes some of https://github.com/pythonarcade/arcade/issues/1796.
Error bc some weird thing, not my PR's problem.

### CODE REVIEW

**Comment by einarf** [comment]
Fixed some conflicts. I assume this one needs pyright to actually pass? mypy definitely doesn't like this unless I missed something important.

**Comment by gran4** [comment]
??????????????? I only added __init__ to the files as the title says. The errors are not created by my PR

**Comment by einarf** [comment]
Some more conflicts to solve here before merge.

**Comment by einarf** [comment]
After a discussion: We don't really want these type annotations in examples and tutorials. That's 90% of the changes here. Adding None return types elsewhere is fine, but it's faster to redo this work than changing ths PR.

**Pull request closed without merging**
