### PR TITLE
Convert README and CONTRIBUTING to Markdown

### PR DESCRIPTION
**Pull request by Cleptomania**
This converts the README and CONTRIBUTING files in the Git repo to use Markdown as discussed in #1910. These are only displayed on the GitHub repo(and the PyPI page) and are not part of the Sphinx docs build, so there's no real reason for them to stay RST, we don't have a need for the extra complexity it adds to them.

### CODE REVIEW

**Comment by Cleptomania** [comment]
Upon further inspection this actually does get used in the docs directly, I didn't realize we were including this file into the doc build. Need to think about that more.

**Comment by einarf** [comment]
Should be easy enough to fix. We can just link to it from the docs. Easy cleanup (TM)

**Comment by Cleptomania** [comment]
Yeah we should be able to just link to the GitHub page for it in the docs, anyone contributing is gonna have to use GitHub anyways so it's not that wild of a re-direct. I'll push a change to docs page to do this soon.

**Comment by Cleptomania** [comment]
This is probably ready to go now, but I'll wait for at least @einarf or @pvcraven to give an okay on merging that we're happy with the changes here. Basically removes most any documentation about contributing from the actual docs, and instead directs to the GitHub CONTRIBUTING file, which is now written in Markdown.

Gives us a single source of truth for the contributing guidelines without having to be dependent on the somewhat fragile include of the CONTRIBUTING file into Sphinx(and the incompatibilities between GitHub and Sphinx's rendering of said file).

**Pull request merged**
