### PR TITLE
WIP: Improve SpriteList doc

### PR DESCRIPTION
**Pull request by pushfoo**
My current intent is to split this into multiple smaller PRs. This one will end up being the `SpriteList` docstring rewrite.

The others:

- [x] #1689 
- [x] #1691 (May still need SpatialHash links?) 
- [x] #1724
- [x] #1770

### CODE REVIEW

**Comment by pushfoo** [comment]
This is blocked by #1639 and will need to be rebased on it

**Comment by pvcraven** [comment]
Might want to consider future PRs  to be smaller. Easier to review for us, quicker to get in, less risk of wasted work.

**Comment by pushfoo** [comment]
> Might want to consider future PRs to be smaller.

Definitely. This PR and #1639 both snowballed into much larger PRs due to being trial runs for concepts which will be applied elsewhere in the codebase.

**Comment by pushfoo** [comment]
I'll just make a new PR for this. Enough has changed or already been incorporated that it's worth another pass.

**Pull request closed without merging**
