### PR TITLE
Improve hitbox drawing(https://github.com/pythonarcade/arcade/issues/1707)

### PR DESCRIPTION
**Pull request by gran4**
Addresses https://github.com/pythonarcade/arcade/issues/1707. Not sure if this is the best way to do it.

### CODE REVIEW

**Comment by einarf** [comment]
This may be a little faster, but it doesn't solve the origonal problem. We don't care about how fast you can debug draw hit box data for a single sprite. We care about drawing speed for an entire sprite list.

It could be better trying to batch some geometry in spritelist,

(Also we removed the ShapeElementList caching of points in the spirte in 3.0. You're just adding back something that was too expensive memory wise and caused GC problems.

Again: You can save a lot of time by discussing things on discord first 😄

**Comment by gran4** [comment]
I thought it was simple. Too simple for discord, but I guess I didn't ge the problem.

**Comment by einarf** [comment]
Like already discussed on discord it needs to be something in the spritelist possibly caching hit box geometry all the sprites in the spritelist, but how do we know the hit box data is dirty? Also: should we just have a bool property to enable debug drawing instead of a separate problem,

@gran4 The reason your suggested solution doesn't really improve the situation much is that this is a GPU based library. Lots of draw class will never be fast no matter how much you optimize it. You might be able to draw 500-1000 hit box points per frame if you are lucky, but when there's 100k sprites in large tilemaps it's going to be slow. We need to batch draw these hit box points. It can be done with ShapeElementList, but again.. there are defniely some challenges here.

**Comment by einarf** [comment]
The code you wanted to add in this PR is basically what we removed in the sprite revamp (3..0).. We want the base sprites to be as light as possible.

**Pull request closed without merging**
