### PR TITLE
Improve and fix docs of GUI system

### PR DESCRIPTION
**Pull request by eschan145**

### CODE REVIEW

**Comment by eschan145** [comment]
I'll add some more commits soon; don't merge immediately.

**Comment by pvcraven** [comment]
Just checking, you can see what the auto-checks are complaining about?

**Comment by eschan145** [comment]
@pvcraven there might be some multiline code stuff that messed it up.

If we had a line of code like:

```
this_line_of_code_is_very_very_very_long_and_needs_to_be_trimmed_down.x += a_random_variable.x * 2 + a_random_number()
```

Then I'm not sure how to wrap it to eighty characters. For now I have only used the blackslash character `\`, but I'm not sure if it's the right way... It's the same with the docs for parameters. Sometimes they exceed 120 characters, and it's really unreadable.

**Comment by pvcraven** [comment]
You can see what it complains about here:
https://github.com/pythonarcade/arcade/actions/runs/4029149776/jobs/6926745746

Run flake8 on your code base to see the issues locally.

**Comment by einarf** [comment]
@eruvanos Is this PR salvagable?

**Comment by eruvanos** [comment]
Yes, we only have to fix the format for failing pep8.
Then we could merge it, or merge it and fix it afterwards.

**Comment by pushfoo** [comment]
In addition to the CI failures, many of the changes in this PR break links to classes and break [PEP-257](https://peps.python.org/pep-0257/#multi-line-docstrings):
> Multi-line docstrings consist of a summary line just like a one-line docstring, followed by a blank line, followed by a more elaborate description. The summary line may be used by automatic indexing tools; it is important that it fits on one line and is separated from the rest of the docstring by a blank line.

Given the original poster (@eschan145) has not responded for a long time, should this PR be considered abandoned and ok to fork / update?

**Comment by eruvanos** [comment]
Merged as #1670

**Pull request closed without merging**
