### PR TITLE
Tile map custom class

### LINKED ISSUE #942: Custom Classes for layers of Tile Map [Enchantment/Feature request]
## Enchantment/Feature request
There should be a way, to define Custom classes for each Layer within a TileMap. All tiles of said layer would be created from that custom class instead of the default Sprite.

### PR DESCRIPTION
**Pull request by CommentatorForAll**
fixes #942 
changed tile map to accept a custom_class layer attribue (default Sprite). When reading in the tilemaps, all Tiles of that layer will be created from that class.

### CODE REVIEW

**Comment by Cleptomania** [comment]
Thanks for the PR on that, I’ll get it merged in sometime tonight probably. I’m going to expand this to be able to set it on a per layer basis as well.

**Comment by CommentatorForAll** [comment]
This is already on layer basis. You can define it for each layer seperately.
The only case which doesnt work is animated sprites. That one is still created from the original animatedspeite one

**Comment by Cleptomania** [comment]
Okay I see now, one potential issue here is that this assumes your custom class constructor expects the same things as the standard Sprite class. I'm certain this is something that would vary a lot from case to case, so I'm not sure I see a great solution to that, any thoughts on that?

One possible way to handle it could be having a `custom_class_args` field in `layer_properties` which is just a dict and we pass it into the constructor with the `**` operator. We would still have to provide the same base args as we do for Sprite, but at least this would let you have additonal parameters.

This would mean if for example you had two layers of Platforms, which derive from the same base class, but maybe they're destructible and have different health values, you might do something like:

```python
layer_options = {
    "low_health_platforms": {
        "custom_class": MyPlatform,
        "custom_class_args": {
            "health": 50
        }
    },
    "high_health_platforms": {
        "custom_class": MyPlatform,
        "custom_class_args": {
            "health": 100
        }
    },
}
```

This still requires your `__init__` of the custom class to accept the regular stuff that `arcade.Sprite` does though, but that might be fine, even if you wanna actually create the Sprite differently or something, you could just make it accept the values and have them be thrown away. I don't really see a better way to handle that, any ideas?

**Comment by CommentatorForAll** [comment]
That is a valid argument. I was tinkering with that too, because beforehand, i had custom argumetns too. But i figured that it would be best if one assumes, that the custom constructor is compatible with the default sprite constructor. but yeah, custom argumetns would be nice ^^

**Comment by Cleptomania** [comment]
Gonna merge this in now, I'll do some more testing of the custom class args and see if we need any tweaks on the dev branch then

**Pull request merged**
