### PR TITLE
Section little changes and 2 examples more

### PR DESCRIPTION
**Pull request by alejcas**
Section changes: 

- dynamically return the window even if the section is not yet attached to the view.
- accept_keyboard_events is now True by default

I've added 2 more examples and reorganized examples.

Let me know what you think about the examples.

Also, I renamed the example file and that changed [util/update_quick_index.py](https://github.com/pythonarcade/arcade/compare/development...janscas:sections?expand=1#diff-2153cdcc45ed465f8959a4356fd4145f2634f371f7b7488e565e4a73fb12fdf1), I dont' know how to change that file to add the 2 new example files. Now just shows the first example now renamed as "section_demo_3.py".

### CODE REVIEW

**Comment by pvcraven** [comment]
Comments left for some minor things to sort out. Because of the narrow width of the doc pages, I'd set a guide to about 80 characters, or at least take a look how far you can go before the user has to scroll in a window that isn't set up for it.

**Comment by alejcas** [comment]
> Comments left for some minor things to sort out

Where are these comments?

**Comment by pvcraven** [comment]
> Where are these comments?

Click on "Files Changed" in the PR, and scroll down.

**Comment by alejcas** [comment]
I'm sorry I don't see anything ...

image

**Comment by pvcraven** [comment]
Hm, I appear not to know how to use the 'review' part of the PR then. For now, I'll just paste here:

**Comment by alejcas** [comment]
@pvcraven ok, I've just submit a change with the line length fixed to pep8 standards and another one changing update_quick_index (sorry for that).

**Comment by alejcas** [comment]
@pvcraven can you confirm that the new examples are enough?

**Comment by pvcraven** [comment]
Not sure until I get more time. Can you look at the build check errors?

**Comment by alejcas** [comment]
Sure!

**Comment by alejcas** [comment]
I hate with all my soul the pep8 line length limit...

**Comment by alejcas** [comment]
Hi @pvcraven if something is missing please let me know.

thanks

**Pull request merged**
