### PR TITLE
Style follow-up to #1681

### PR DESCRIPTION
**Pull request by pushfoo**
Follows upon #1681 with some minor styling tweaks as [mentioned in the comments ](https://github.com/pythonarcade/arcade/pull/1681#pullrequestreview-1394976558).

Ty to Clepto for already grabbing some of the lingering styling issues!

### CODE REVIEW

**Comment by Cleptomania** [comment]
Is this ready to go or is there more to fix here?

**Comment by pushfoo** [comment]
tl;dr Yes

The main thing I wanted to address is was this indent: https://github.com/pythonarcade/arcade/blob/26d05eb6bcd5e0ff7dc83cc3fd5d4e1a59bf1402/arcade/text.py#L15-L19

The rest is spacing / ordering that's fairly inconsistent across the repo anyway, such as:

*  LOG / `__all__` / etc ordering
* Spacing style
 
I'll hold off on homogenizing top-of-file style beyond the bare minimum until we have time to discuss & add a more detailed style guide section for the Programming/Contributing Guide.

**Comment by Cleptomania** [comment]
> I'll hold off on homogenizing top-of-file style beyond the bare minimum until we have time to discuss & add a more detailed style guide section for the Programming/Contributing Guide.

This is probably better suited as a discussion about using an auto-formatter(like black), but I agree that can be handled separately.

**Comment by pushfoo** [comment]
> Using an auto-formatter(like black)

This may be why whitespace linting isn't enabled on `ruff` by default.

**Pull request merged**
