### PR TITLE
Adding global_options argument to TileMap class

### PR DESCRIPTION
**Pull request by EnlNovius**
Proposed code for the issue 921: [https://github.com/pythonarcade/arcade/issues/921](https://github.com/pythonarcade/arcade/issues/921)

### CODE REVIEW

**Comment by Cleptomania** [comment]
I think a better approach is to set these as attributes of the class individually. We already have `TileMap.scaling` which provides a global default for scaling of a layer specific one isn’t set. I think any global options should follow this same structure. It’s much easier to document and for people to find what options are available this way.

the dict way for layer specific options was only really handled that way out of necessity

We could take these in the constructor, and then construct a dict for each layer with the values from the layer options dict or insert the global option if it’s not there.

**Comment by EnlNovius** [comment]
Something like this in the constructor parameters ? 

```
use_spatial_hash: bool = False,
hit_box_algorithm: str = "Simple",
hit_box_detail: float = 4.5,
```

Or should these parameters be optional?

**Comment by EnlNovius** [comment]
New commit with parameters.

By the way, `PIL` is import but probably not used in the tilemap.py

**Comment by Cleptomania** [comment]
I'm merging this but I'm going to change a little bit how it applies the global values to the layers. API still the same though.

**Pull request merged**
