### PR TITLE
Update snow.py

### PR DESCRIPTION
**Pull request by feiyuhuahuo**
update() takes no arg

### CODE REVIEW

**Comment by pushfoo** [comment]
Can you explain the reasoning on this + #2315?

My understanding of https://github.com/pythonarcade/arcade/pull/2288/ is:
* The `update` function now takes an optional `delta_time` keyword
* `on_update` is now a deprecated wrapper around it

**Comment by einarf** [comment]
> update() takes no arg

`update()` takes arguments in version 3.0. You should use the `development` branch directly, `3.0.0.dev31` or later.

**Comment by einarf** [comment]
See: 
https://github.com/pythonarcade/arcade/blob/fa6e9387cb9801081f378a4b4e978028ea531bd8/arcade/sprite/base.py#L581-L591

**Comment by feiyuhuahuo** [comment]
I do run on `3.0.0.dev31`, the example code just can not run. 
image
The SpriteList.update() takes no arg. Same  as #2315

**Comment by einarf** [comment]
Hey. Sorry, I should have said install the development branch, but dev32 should be out not with these changes 😄

**Pull request closed without merging**
