### PR TITLE
Clarify SpriteSolidColor and SpriteCircle docstrings

### PR DESCRIPTION
**Pull request by pushfoo**
Built & tested locally.

This PR clarifies the `SpriteSolidColor` and `SpriteCircle` docstrings by making the following changes:
* Use more precise language in describing the shapes (circle instead of ellipse)
* Succinctly explain the user impact of the texture generation & caching behavior
* Explain the direction of the gradient for `SpriteCircle`
* Sync the types of arguments and their annotation in the docstrings

### CODE REVIEW

**Comment by einarf** [comment]
I'll just merge this. We can update when we change it to only make white textures.

**Comment by pushfoo** [comment]
@einarf I think we might want to set color to a keyword arg to get the best of both worlds.

**Comment by einarf** [comment]
Should not be a problem. Default white then?

**Comment by pushfoo** [comment]
Yes, for both of them. I'd also like to take consider changing some of the related underlying functionality after I finish my current experiment and reflect on it for a bit.

**Pull request merged**
