### PR TITLE
Added `on_mouse_enter` and `on_mouse_leave` to `View`

### PR DESCRIPTION
**Pull request by alejcas**
I don't know why `View` doesn't implement `on_mouse_enter` and `on_mouse_leave`.

Here I just add that for the `View`

### CODE REVIEW

**Comment by einarf** [comment]
Should we also add a wrapper for this in the `Window` so it gets exposed in arcade docs?

**Comment by alejcas** [comment]
> Should we also add a wrapper for this in the `Window` so it gets exposed in arcade docs?

Don't know what you mean... sorry

**Comment by einarf** [comment]
I mean just adding the same function to `Window`. This means arcade docs will inform the user about the existance of this event. It seems weird that only `View` would have it.

**Comment by alejcas** [comment]
ahh ok, the Window already have these methods. It's weird to me that View didn't.
Maybe it's something intentional?

I tried and if I define those in a View subclass they work as expected.

**Comment by einarf** [comment]
Just add the same methods to `Window` so these callbacks are exposed in arcade docs. Most arcade users don't know that pyglet exists and it makes sense to add them in both places.

**Comment by alejcas** [comment]
Ok!

**Comment by einarf** [comment]
Awsome. Then we can tell the world that Alejandro added this great new feature in patch notes 🎉

**Comment by alejcas** [comment]
> Awsome. Then we can tell the world that Alejandro added this great new feature in patch notes 🎉

yeah that took me a lot amount of work! ;)

**Pull request merged**
