### PR TITLE
Configured optimizely web experiment snippet

### PR DESCRIPTION
**Pull request by Matt-Burns**

### CODE REVIEW

**Comment by einarf** [comment]
Any more context for this pull request?

**Comment by Matt-Burns** [comment]
I am a CIS-385 student working with Paul Craven. This change will integrate https://api.arcade.academy/en/latest/ with Optimizely Web Experimentation

**Comment by pvcraven** [comment]
Matt, this has been deployed to the development branch here:
https://api.arcade.academy/en/development/

This is NOT the branch where most of the traffic is. Please make sure it is working first. If it is, we'll move to the main branch.
Don't forget to add comments to a pull request. Otherwise it looks a bit questionable.

einarf, this is a product I've got a student doing research on. Allows A/B testing.

**Comment by einarf** [comment]
Good to know. This sounds very useful.

**Comment by Matt-Burns** [comment]
Dev is integrated with Optimizely. Clear any history you have with https://api.arcade.academy/en/development/ then go to the site. You should see different python pics

**Comment by pvcraven** [comment]
Great. I'll move it to the main site soon. We need to come up with A/B tests. Just remember you are editing a real, live site, so don't get too weird.

**Pull request merged**
