### PR TITLE
Added validation to UIInputText

### PR DESCRIPTION
**Pull request by eschan145**
The validation limits what the user can type. For example, if the parameter validate is set to "0123456789", the user can only type numerical digits into the input. The maximum parameter is the maximum number of characters the user can input.

### CODE REVIEW

**Comment by Ibrahim2750mi** [comment]
#1118

**Comment by eruvanos** [comment]
Will have a look on it

**Comment by pushfoo** [comment]
I'm not sure that this PR's approach is the best in the long run. I mentioned it as a [comment on #1118](https://github.com/pythonarcade/arcade/issues/1118#issuecomment-1115422519), but tl;dr I think we should use callables as the validator arguments. The functionality included in this PR could be one of the default validator callables we provide to users.

**Comment by pvcraven** [comment]
I think input validation will need a lot more thought on how (of if) we want to manage it in the main library.

**Pull request closed without merging**
