### PR TITLE
Delete SimpleCamera

### PR DESCRIPTION
**Pull request by pushfoo**
## Changes

1. Remove `SimpleCamera` from `arcade.camera`'s `__init__.py`
2. Delete the `simple_camera.py` file itself

## Why

TL;DR: We'd have to rewrite `SimpleCamera` again + [Discord discussion](https://discord.com/channels/458662222697070613/1211328349369274479/1226338213023580192) suggests [nobody actually wants SimpleCamera around](https://en.wikipedia.org/wiki/Abilene_paradox)

### It's Not Actually 2.6 Compatible

The current `SimpleCamera` isn't API-compatible with 2.6. Instead, it's a rewrite of a rewrite started before 3.0. See the blue forks on this timeline (credit goes to @DigiDuncan):
image
*Green is `development`, yellow appears to be WIP code*

### Nothing Actually Uses It

- [x] [Chesterton's Fence](https://grugbrain.dev/#grug-on-chestertons-fence) Checks: satisfied
  - [x] Nothing actually uses it in the examples or anywhere else
  - [x] It's not referenced in the doc
  - [x] There's no usage outside an import in `arcade.camera` 
  - [x] Tutorials fully updated as they can be pending #2055 

### `Camera2D.from_raw_data` is the best porting option

TL;DR: Add migration guide showing how to convert code to use the class method

| Core Concept | How `SimpleCamera` Fails to Deliver |
|-------|---------|
| 2.6-compatible arguments | Current implementation needs rewrite to be 2.6-comaptible |
| `move_to` / `update` methods | Broken behavior replaced by grips and controllers +  `update` doesn't accept a time step |

### Other compatibility approaches were disliked

The following options were disliked in Discord discussion:
| Option | Reason(s) for Dislike |
|----------|--------------------------|
| `Camera` which acts like 2.6 but logs deprecation warning to console | People will expect future compatibility, console warnings might get missed |
| `Camera` import raises an `ImportError` on use + links a migration guide | A broken import in the default library is ugly |
| Rewriting for compatibility yet another time | We have already done this too many times |

### CODE REVIEW

**Comment by DigiDuncan** [comment]
Huge +1.

**Comment by pushfoo** [comment]
The CI failures are pyright being angry about the GUI again.

**Comment by pushfoo** [comment]
We can still merge this if we want, but the platformer tutorial still references `SimpleCamera`. PyCharm's search scoping may have excluded .rst when I looked.

**Comment by alejcas** [comment]
There's no reasons to have simplecamera with carmera2d

**Comment by einarf** [comment]
Good stuff 👍

**Pull request merged**
